describe("Elements", function()
    local elements

    before_each(function()
        -- Load the elements module
        elements = require("sage.ui.elements")
    end)

    describe("TextElement", function()
        it("should create a text element", function()
            local elem = elements.TextElement.new("test", "hello")
            assert.equals("hello", elem.value)
            assert.equals("hello", elem:render())
        end)

        it("should update value", function()
            local elem = elements.TextElement.new("test", "hello")
            local changed = elem:update("world")
            assert.is_true(changed)
            assert.equals("world", elem.value)
        end)

        it("should not mark as dirty if value unchanged", function()
            local elem = elements.TextElement.new("test", "hello")
            local changed = elem:update("hello")
            assert.is_false(changed)
        end)
    end)

    describe("StatusElement", function()
        it("should render icon by default", function()
            local elem = elements.StatusElement.new("status", "loaded", "icon")
            local result = elem:render()
            assert.is_not_nil(result)
            assert.is_string(result)
        end)

        it("should render with highlight", function()
            local elem = elements.StatusElement.new("status", "loaded", "icon")
            local result = elem:render_with_hl()
            assert.equals("table", type(result))
            assert.is_not_nil(result.text)
            assert.is_not_nil(result.hl_group)
        end)

        it("should use status-specific highlights", function()
            local elem = elements.StatusElement.new("status", "loaded", "icon")
            local result = elem:render_with_hl()
            assert.equals("SageStatusLoaded", result.hl_group)
        end)

        it("should handle failed status", function()
            local elem = elements.StatusElement.new("status", "failed", "icon")
            local result = elem:render_with_hl()
            assert.equals("SageStatusFailed", result.hl_group)
        end)
    end)

    describe("StageElement", function()
        it("should render stage icon", function()
            local elem = elements.StageElement.new("stage", "now", "icon")
            local result = elem:render()
            assert.is_not_nil(result)
        end)

        it("should render stage with text", function()
            local elem = elements.StageElement.new("stage", "now", "icon_text")
            local result = elem:render()
            assert.is_string(result)
            assert.is_true(#result > 0)
        end)
    end)

    describe("DurationElement", function()
        it("should render duration in milliseconds", function()
            local elem = elements.DurationElement.new("duration", 123.45)
            local result = elem:render()
            assert.equals("123.45ms", result)
        end)

        it("should handle zero duration", function()
            local elem = elements.DurationElement.new("duration", 0)
            local result = elem:render()
            assert.equals("0.00ms", result)
        end)

        it("should handle nil duration", function()
            local elem = elements.DurationElement.new("duration", nil)
            local result = elem:render()
            assert.equals("", result)
        end)
    end)

    describe("ListElement", function()
        it("should create empty list", function()
            local elem = elements.ListElement.new("list", nil)
            assert.equals(0, elem:count())
        end)

        it("should add items", function()
            local elem = elements.ListElement.new("list", nil)
            elem:add("item1")
            elem:add("item2")
            assert.equals(2, elem:count())
        end)

        it("should render as comma-separated", function()
            local elem = elements.ListElement.new("list", { "a", "b", "c" })
            local result = elem:render()
            assert.equals("a, b, c", result)
        end)

        it("should check if has item", function()
            local elem = elements.ListElement.new("list", { "test" })
            assert.is_true(elem:has("test"))
            assert.is_false(elem:has("other"))
        end)

        it("should remove items", function()
            local elem = elements.ListElement.new("list", { "a", "b", "c" })
            elem:remove("b")
            assert.equals(2, elem:count())
            assert.is_false(elem:has("b"))
        end)

        it("should render buttons", function()
            local elem = elements.ListElement.new("list", { "dep1", "dep2" })
            local buttons = elem:render_buttons()
            assert.equals(2, #buttons)
            assert.is_string(buttons[1])
            assert.is_string(buttons[2])
        end)
    end)

    describe("LazyElement", function()
        it("should render empty if no triggers", function()
            local elem = elements.LazyElement.new("lazy", nil)
            local result = elem:render()
            assert.equals("", result)
        end)

        it("should render command triggers", function()
            local elem = elements.LazyElement.new("lazy", {
                cmds = { "Telescope" },
            })
            local result = elem:render()
            assert.is_not_nil(result)
            assert.is_true(#result > 0)
            assert.is_true(result:find("cmd") ~= nil or result:find("Telescope") ~= nil)
        end)

        it("should render event triggers", function()
            local elem = elements.LazyElement.new("lazy", {
                events = { "BufReadPost", "BufNewFile" },
            })
            local result = elem:render()
            assert.is_not_nil(result)
            assert.is_true(#result > 0)
        end)

        it("should render filetype triggers", function()
            local elem = elements.LazyElement.new("lazy", {
                fts = { "lua", "vim" },
            })
            local result = elem:render()
            assert.is_not_nil(result)
            assert.is_true(result:find("ft") ~= nil)
        end)

        it("should render with highlights", function()
            local elem = elements.LazyElement.new("lazy", {
                cmds = { "Test" },
            })
            local result = elem:render_with_hl()
            assert.equals("table", type(result))
            assert.is_true(#result > 0)
            assert.is_not_nil(result[1].text)
            assert.is_not_nil(result[1].hl_group)
        end)

        it("should truncate long lists", function()
            local elem = elements.LazyElement.new("lazy", {
                cmds = { "Cmd1", "Cmd2", "Cmd3", "Cmd4", "Cmd5" },
            })
            local result = elem:render()
            assert.is_true(result:find("+") ~= nil)
        end)

        it("should get trigger info", function()
            local elem = elements.LazyElement.new("lazy", {
                cmds = { "Test1", "Test2" },
            })
            local info = elem:get_info()
            assert.equals("cmds", info.type)
            assert.equals(2, info.count)
            assert.equals("table", type(info.values))
        end)
    end)

    describe("BooleanElement", function()
        it("should render true value", function()
            local elem = elements.BooleanElement.new("bool", true)
            local result = elem:render()
            assert.is_not_nil(result)
        end)

        it("should render false value", function()
            local elem = elements.BooleanElement.new("bool", false)
            local result = elem:render()
            assert.is_not_nil(result)
        end)

        it("should use custom true/false text", function()
            local elem = elements.BooleanElement.new("bool", true, "YES", "NO")
            assert.equals("YES", elem:render())
            elem:update(false)
            assert.equals("NO", elem:render())
        end)
    end)

    describe("ErrorElement", function()
        it("should render empty for empty error", function()
            local elem = elements.ErrorElement.new("error", "")
            local result = elem:render()
            assert.equals("", result)
        end)

        it("should render error message", function()
            local elem = elements.ErrorElement.new("error", "Test error")
            local result = elem:render()
            assert.is_true(#result > 0)
            assert.is_true(result:find("TEST ERROR") ~= nil)
        end)

        it("should use error highlight", function()
            local elem = elements.ErrorElement.new("error", "Test")
            local result = elem:render_with_hl()
            assert.equals("SageStatusFailed", result.hl_group)
        end)
    end)

    describe("Element base class", function()
        it("should handle visibility", function()
            local elem = elements.TextElement.new("test", "hello")
            elem:set_visible(false)
            assert.equals("", elem:render())
        end)

        it("should track dirty state", function()
            local elem = elements.TextElement.new("test", "hello")
            assert.is_false(elem:is_dirty())
            elem:update("world")
            assert.is_true(elem:is_dirty())
            elem:mark_clean()
            assert.is_false(elem:is_dirty())
        end)

        it("should support custom formatter", function()
            local elem = elements.TextElement.new("test", "hello")
            elem:set_formatter(function(val)
                return val:upper()
            end)
            assert.equals("HELLO", elem:render())
        end)
    end)
end)
